spring/spring-website

- wwwroot/phpbb/styles/prosilver/theme/colours.css
FWIW also kills 2 http calls and "improves performance" (lol)
http://i.imgur.com/nTUAKiW.png
> Change forum bg gradients to match the site

- wwwroot/phpbb/styles/prosilver/theme/common.css
- wwwroot/phpbb/styles/prosilver/theme/content.css
Fix responsive on tablet and mobile devices
http://i.imgur.com/c7sh48H.png
> Fix responsiveness

- wwwroot/phpbb/styles/prosilver/theme/content.css
http://i.imgur.com/bKfCNja.png
> Fix responsive view for topic lists

- wwwroot/phpbb/styles/prosilver/theme/content.css
- wwwroot/phpbb/styles/prosilver/theme/responsive.css
Remove min-width from wrap which caused horizontal scrollbars on iphones (seriously, whatever phpbb dev wrote that stylesheet must have been drinking that night)
> Make search box more attractively placed on tablet/mobile

- wwwroot/phpbb/styles/prosilver/theme/content.css
- wwwroot/phpbb/styles/prosilver/theme/responsive.css
Before: http://i.imgur.com/B3OsmMu.png
After: http://i.imgur.com/qBO8FNy.png
> Fix wrapper div and iphone layouts

- wwwroot/phpbb/styles/prosilver/theme/content.css
Fix postbox for phones/responsive: http://i.imgur.com/iL0M1Sg.png / http://i.imgur.com/iPaeN9G.png
Fix avatar panel for responsive: http://i.imgur.com/uszWIyO.png
> Fix posting box on phones (and in general) / Fix avatar panel on phones

- wwwroot/phpbb/styles/spring/theme/overrides.css
Fix index info responsiveness
before: http://i.imgur.com/fUz6pbk.png
after: http://i.imgur.com/MO7R04n.png
> Fix responsiveness of time and date info on board index

- wwwroot/phpbb/styles/spring/theme/overrides.css
Before: http://i.imgur.com/eew5REf.png
After: http://i.imgur.com/BiNc5GF.png
> Make inline attachments more attractive

- wwwroot/phpbb/styles/spring/theme/overrides.css
Attachbox before: http://i.imgur.com/79wM0lL.png
Attachbox after: http://i.imgur.com/SuBLzWx.png
Buttons before: http://i.imgur.com/p0ugmg0.png
Buttons after: http://i.imgur.com/OCWERPo.png
> Fix attach box responsiveness and add TOC + sexybuttons

- wwwroot/phpbb/styles/spring/theme/overrides.css
Before: http://i.imgur.com/DNQuoes.png
After: http://i.imgur.com/woxXeFC.png
> Convert pagination to sexy new buttons

- wwwroot/phpbb/styles/spring/theme/overrides.css
http://i.imgur.com/lOL45CF.png
http://i.imgur.com/9oXErpH.png
> Change links to be less obvious

- wwwroot/phpbb/styles/spring/theme/overrides.css
Easier to see what page you're on: http://i.imgur.com/fhQKGyR.png
> Make pagination more obvious, fix typos.

- wwwroot/phpbb/styles/spring/theme/common.css
- wwwroot/phpbb/styles/spring/theme/normalize.css
- wwwroot/phpbb/styles/spring/theme/overrides.css
- wwwroot/phpbb/styles/spring/theme/stylesheet.css
Before: http://i.imgur.com/DT4RDLu.png
After: http://i.imgur.com/jdPoDld.png
> Fix pagination on responsive

- wwwroot/phpbb/styles/spring/theme/overrides.css
Before: http://i.imgur.com/nR5VDkl.png
After: http://i.imgur.com/mMd0ebd.png
> Fix silly wrap margins

- wwwroot/header-navbar-wiki-overrides.css
- wwwroot/mediawiki/skins/SpringNew.php
- wwwroot/phpbb/styles/spring/theme/header-navbar.css
Wheeee.
Related to: https://github.com/spring/spring-website/pull/49
> Fix navbar on wiki

- wwwroot/header-navbar-mainsite-overrides.css
- wwwroot/index.php
- wwwroot/phpbb/styles/spring/theme/header-navbar.css
- wwwroot/templates/header-offsite.html
- wwwroot/templates/meta.html
Fix 1 pixel offset of wiki navbar
Add navbar to mainsite
Change absolute path to logo to be relative
Fix line height on navbar list items
> Navbar positioning, addition to mainsite, fix spring logo path

- wwwroot/header-navbar-mainsite-overrides.css
- wwwroot/header-navbar-media-overrides.css
- wwwroot/header-navbar-wiki-overrides.css
Fixed the pixel offsets ... again -_-
> Aligning menu items

- wwwroot/index.css
> Fix my bandaid with code that doesn't suck

- wwwroot/phpbb/styles/spring/theme/materialish.css
- wwwroot/phpbb/styles/spring/theme/overrides.css
And make it not be ugly on mobile.
> Fix paddings to match the rest of the site

- .gitmodules
I suggest we add an upvote system for the forum and a syntax highlight system for both the forum and wiki.  Related mantis feature requests: https://springrts.com/mantis/view.php?id=4992 and https://springrts.com/mantis/view.php?id=4994
I've already made the forum changes, but this should be done for the wiki :https://www.mediawiki.org/wiki/Extension:SyntaxHighlight_GeSHi . 
Before I attempt it, why are we using an old version of MediaWiki (1.19.24)? The new version already comes bundled with it so it would be good to upgrade it. Should we just do this?
> Modernize forum

- wwwroot/imagerotate.php
- wwwroot/includes/bbcode.php
- wwwroot/includes/cache.php
- wwwroot/includes/db.php
- wwwroot/includes/news.php
- wwwroot/includes/thumbs.php
- wwwroot/index.php
- wwwroot/media.php
- wwwroot/redirect.php
- wwwroot/screenshot.php
- wwwroot/templates/footer.html
- wwwroot/templates/frontpage.html
- wwwroot/templates/header-offsite.html
- Remove tables from the homepage, replaced with div containers
- Switch from mysql to mysqli ( mysql is a deprecated extension, unavailable in newer versions of PHP )
- Error checking and handling added in several places
- Nav menu items removed, some renamed as discussed on the forums
- Changed the footer to credit the contributors on GitHub
- Some minor improvements with https
> Homepage and General fixes

- wwwroot/phpbb/styles/spring/theme/materialish.css
Screenshots showing the changes:
http://imgur.com/a/Kne5w
> Fix for UserCP and attachment box on posting

- wwwroot/phpbb/styles/spring/theme/materialish.css
Fix for the left side of posts in the posts/topic review box being slightly too large
> Fix topic review box

- wwwroot/index.css
- wwwroot/templates/frontpage.html
Fix the homepage buttons orientation, remove a handful of styles, fix an issue with maximum widths of the buttons
> Styling update

- wwwroot/index.css
update front page news css with improved header highlight and content separation
> update front page news css

- wwwroot/templates/newsitem.html
Actual meaningful tags for the news items
> Use headings for the headings
